version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: note_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: note_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/notesdb
    depends_on:
      - db

volumes:
  postgres-data: